### ISSUE TITLE
xss + sql injection

### ISSUE THREAD

**Issue by deFming** [opensec-cn/vtest#2]
![26331556080339_ pic_hd](https://user-images.githubusercontent.com/27653537/56634515-dc604380-6694-11e9-9d9e-b3d7e62bfae3.jpg)
xss
![26341556080344_ pic_hd](https://user-images.githubusercontent.com/27653537/56634529-e5511500-6694-11e9-9809-d9303929ac98.jpg)

注入  
body参数
![26351556080349_ pic_hd](https://user-images.githubusercontent.com/27653537/56634537-ed10b980-6694-11e9-8612-2d32dd44f83b.jpg)
body参数直接获取，没有过滤，并入查询，导致注入
![image](https://user-images.githubusercontent.com/27653537/56634567-06b20100-6695-11e9-8dec-d0c5009ea32d.png)

**Comment by zhengjim** [comment]
666

**Comment by ywolf** [comment]
感谢提醒
