### ISSUE TITLE
请教一下:POST 的数据接收失败

### ISSUE THREAD

**Issue by evi1ox** [opensec-cn/vtest#3]
是不是哪里部署有问题(ns 记录之类的)..接收不到 post 数据..
![image](https://user-images.githubusercontent.com/24634543/57203952-c896d480-6fe6-11e9-93be-34b150bd9594.png)

**Comment by ywolf** [comment]
完整的原始请求包 发一下看看 我测试一下

**Comment by ywolf** [comment]
域名可以打码掉

**Comment by evi1ox** [comment]
![image](https://user-images.githubusercontent.com/24634543/57204642-a489c200-6feb-11e9-943e-dc8fa8dd9d5d.png)
第一张图片:里面是 GET
第二张图片:POST 
![image](https://user-images.githubusercontent.com/24634543/57204668-c6834480-6feb-11e9-9d55-072dc2703a8f.png)


```
POST /httplog/testd.php?id=1 HTTP/1.1
Host: vul.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Content-Length: 15
Connection: close
Upgrade-Insecure-Requests: 1

s=system('ls');
```
