### ISSUE TITLE
求教一下所有IP的地址都是127.0.0.1

### ISSUE THREAD

**Issue by kb-8-byte** [opensec-cn/vtest#4]
![image](https://user-images.githubusercontent.com/18651522/57355303-4baf5a80-71a0-11e9-8d68-c766ee09731c.png)

**Comment by ywolf** [comment]
用根域名哦

**Comment by ywolf** [comment]
启动的时候填的根域名

**Comment by kb-8-byte** [comment]
![image](https://user-images.githubusercontent.com/18651522/57362858-478c3880-71b2-11e9-8a7c-a7446aefd1c4.png)
是填根域名的，

**Comment by ywolf** [comment]
dns请求不要带上子域名 例如 11.11.11.11.webscan.ink

**Comment by kb-8-byte** [comment]
打扰一下，还是不是，我想看一下你怎么解析的，我这样解析有问题吗
![image](https://user-images.githubusercontent.com/18651522/57364368-9be4e780-71b5-11e9-9925-1d66e5b5af8f.png)

**Comment by ywolf** [comment]
最新版本已解决此问题
