### ISSUE TITLE
关于TOKEN硬编码

### ISSUE THREAD

**Issue by ldqsmile** [opensec-cn/vtest#9]
看了下，貌似目前API_TOKEN是硬编码的，PASSWORD写死了。

PASSWORD = 'admin'
API_TOKEN = md5("ded08972cead38d6ed8f485e5b65b4b6" + PASSWORD)

**Comment by ywolf** [comment]
这是默认密码 启动脚本的时候 -p 定义密码

**Comment by ywolf** [comment]
仔细看了下 问题确实存在 已经修复
